import {
  upgradeButtonPointerEvents,
  upgradeButtonStyleUpdate,
} from "../utils/buttonStyles";

export function upgradeButtons(scene, sizer, upgrades, topbar) {
  const buttons = [];

  upgrades.forEach((upgrade) => {
    const upgradeButton = scene.rexUI.add.label({
      background: scene.rexUI.add.roundRectangle(
        0, // X position
        0, // Y position
        200, // Width
        50, // Height
        10, // Border radius
        0xf4c6c6 // Background color
      ),
      width: 200,
      height: 50,
      text: scene.add.text(0, 0, upgrade.name, {
        fontSize: "18px",
        color: "#000000",
        fontFamily: "Lato",
        backgroundColor: "#F4C6C6",
        padding: {
          left: 5,
        },
      }),
    });

    sizer.add(upgradeButton, 0, "center", {
      top: 20,
      left: 270,
      right: 10,
    });

    upgradeButton.setInteractive({ useHandCursor: true });

    // Store each button to be able to reference later
    buttons.push(upgradeButton);

    // Update the style of the upgrade button based on pointerover/pointerout events
    upgradeButtonPointerEvents(upgradeButton, upgrade);

    // Add functionality to activate the upgrades here

    // Logic for activating the Prayer Efficiency upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Prayer Efficiency" &&
        scene.totalFaith >= 50 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 50;
        topbar.updateFaithLabel(scene.totalFaith);
        upgradeButtonPointerEvents(upgradeButton, upgrade);

        // Update the amount of faith generated by clicking on the sprite
        scene.acolyte.off("pointerdown");
        scene.acolyte.on("pointerdown", () => {
          if (upgrade.active === true) {
            scene.totalFaith += 2;
          } else {
            scene.totalFaith += 1;
          }
          topbar.updateFaithLabel(scene.totalFaith);
        });
      }
    });

    // Logic for activating the Prayer Automation upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Prayer Automation" &&
        scene.totalFaith >= 20 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 20;
        topbar.updateFaithLabel(scene.totalFaith);
        upgradeButtonPointerEvents(upgradeButton, upgrade);

        // Start passive faith generation if it doesn't already exist
        if (
          upgrade.name === "Prayer Automation" &&
          !scene.prayerAutomationFaithEvent
        ) {
          scene.prayerAutomationFaithEvent = scene.time.addEvent({
            delay: 1000, // 1 seconds
            callback: () => {
              if (upgrade.active) {
                scene.totalFaith++;
                topbar.updateFaithLabel(scene.totalFaith);
              }
            },
            loop: true,
          });
        }
      }
    });

    // Logic for activating the Basic Rituals upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Basic Rituals" &&
        scene.totalFaith >= 200 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 200;
        topbar.updateFaithLabel(scene.totalFaith);
        upgradeButtonPointerEvents(upgradeButton, upgrade);

        // Temporary Passive Faith Boost Logic
        // If the passive faith generation event is not active, start it at the increased rate for 1 minute
        if (upgrade.name === "Basic Rituals" && !scene.basicRitualsFaithEvent) {
          // Start passive faith generation temporarily at the increased rate
          scene.basicRitualsFaithEvent = scene.time.addEvent({
            delay: 50, // .05 seconds
            callback: () => {
              scene.totalFaith++;
              topbar.updateFaithLabel(scene.totalFaith);
            },
            loop: true,
          });

          // Stop passive faith generation after 1 minute & reset to original button state
          scene.time.delayedCall(60000, () => {
            scene.basicRitualsFaithEvent.remove();
            scene.basicRitualsFaithEvent = null;
            upgrade.active = false;
            upgradeButtonStyleUpdate(upgradeButton, upgrade);
          });
        }
      }
    });

    // Logic for activating the Recruit Followers upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Recruit Followers" &&
        scene.totalFaith >= 300 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 300;
        topbar.updateFaithLabel(scene.totalFaith);
        upgradeButtonPointerEvents(upgradeButton, upgrade);

        // Increase the total number of followers by 50
        scene.totalFollowers += 50;
        // Update the total followers label
        topbar.updateFollowersLabel(scene.totalFollowers);
        // Increase the faith generation by 50 (1 faith per follower)
        if (
          upgrade.name === "Recruit Followers" &&
          !scene.recruitFollowersFaithEvent
        ) {
          scene.recruitFollowersFaithEvent = scene.time.addEvent({
            delay: 1000, // 1 second
            callback: () => {
              if (upgrade.active) {
                scene.totalFaith += 50;
                topbar.updateFaithLabel(scene.totalFaith);
              }
            },
            loop: true,
          });
        }
      }
    });
  });
  return buttons;
}
