import {
  pointerEventStyleUpdates,
  upgradeButtonStyleUpdate,
} from "./buttonStyles";

export function createUpgradeButtons(scene, sizer, upgrades, topbar) {
  upgrades.forEach((upgrade) => {
    const upgradeButton = scene.rexUI.add.label({
      background: scene.rexUI.add.roundRectangle(
        0, // X position
        0, // Y position
        200, // Width
        50, // Height
        10, // Border radius
        0xf4c6c6 // Background color
      ),
      width: 200,
      height: 50,
      text: scene.add.text(0, 0, upgrade.name, {
        fontSize: "18px",
        color: "#000000",
        fontFamily: "Lato",
        backgroundColor: "#F4C6C6",
        padding: {
          left: 5,
        },
      }),
    });

    sizer.add(upgradeButton, 0, "center", {
      top: 20,
      left: 270,
      right: 10,
    });

    upgradeButton.setInteractive({ useHandCursor: true });

    // Update the style of the upgrade button based on pointerover/pointerout events
    pointerEventStyleUpdates(upgradeButton, upgrade);

    // Add functionality to activate the upgrades here

    // Logic for activating the Prayer Efficiency upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Prayer Efficiency" &&
        scene.totalFaith >= 50 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 50;
        topbar.updateFaithLabel(this.scene.totalFaith);
        pointerEventStyleUpdates(upgradeButton, upgrade);

        // Update the amount of faith generated by clicking on the sprite
        scene.acolyte.off("pointerdown");
        scene.acolyte.on("pointerdown", () => {
          if (upgrade.active) {
            scene.totalFaith += 2;
          } else {
            scene.totalFaith += 1;
          }
          topbar.updateFaithLabel(this.scene.totalFaith);
        });
      }
    });

    // Logic for activating the Prayer Automation upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Prayer Automation" &&
        scene.totalFaith >= 20 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 20;
        topbar.updateFaithLabel(scene.totalFaith);
        pointerEventStyleUpdates(upgradeButton, upgrade);

        // Start passive faith generation
        if (!scene.passiveFaithEvent) {
          scene.passiveFaithEvent = scene.time.addEvent({
            delay: 500, // .5 seconds
            callback: () => {
              if (upgrade.active) {
                scene.totalFaith++;
                topbar.updateFaithLabel(scene.totalFaith);
              }
            },
            loop: true,
          });
        }
      }
    });

    // Logic for activating the Basic Rituals upgrade
    upgradeButton.on("pointerdown", () => {
      if (
        upgrade.name === "Basic Rituals" &&
        scene.totalFaith >= 200 &&
        !upgrade.active
      ) {
        upgrade.active = true;
        scene.totalFaith -= 200;
        topbar.updateFaithLabel(scene.totalFaith);
        pointerEventStyleUpdates(upgradeButton, upgrade);

        // Temporary Passive Faith Boost Logic
        // If the passive faith generation event is already active, increase the rate for 1 minute
        if (upgrade.name === "Basic Rituals" && scene.passiveFaithEvent) {
          const originalDelay = scene.passiveFaithEvent.delay;

          // Increase passive faith generation rate
          scene.passiveFaithEvent.delay *= 0.05; // 20 times faster

          // Reset to original delay after 1 minute & reset to original button state
          scene.time.delayedCall(60000, () => {
            scene.passiveFaithEvent.delay = originalDelay;
            upgrade.active = false;
            upgradeButtonStyleUpdate(upgradeButton, upgrade);
          });
        }
        // If the passive faith generation event is not active, start it at the increased rate for 1 minute
        else if (upgrade.name === "Basic Rituals" && !scene.passiveFaithEvent) {
          // Start passive faith generation temporarily at the increased rate
          scene.passiveFaithEvent = scene.time.addEvent({
            delay: 50, // .05 seconds or 20 times faster
            callback: () => {
              scene.totalFaith++;
              topbar.updateFaithLabel(scene.totalFaith);
            },
            loop: true,
          });

          // Stop passive faith generation after 1 minute & reset to original button state
          scene.time.delayedCall(60000, () => {
            scene.passiveFaithEvent.remove();
            scene.passiveFaithEvent = null;
            upgrade.active = false;
            upgradeButtonStyleUpdate(upgradeButton, upgrade);
          });
        }
      }
    });

    // Logic for activating the Recruit Followers upgrade
  });
}
